image: node:lts-jessie

stages:
  - test

audit:
  stage: test
  script:
    - cd src/server
    - npm audit
  only:
    - merge_requests
    - master
  except:
    - branches

lint-server:
  stage: test
  script:
    - npm install -g eslint eslint-plugin-prettier prettier babel-eslint
    - cd src/server
    - eslint . 
  only:
    - merge_requests
    - master
  except:
    - branches

lint-client:
  stage: test
  script:
    - npm install -g eslint eslint-plugin-prettier prettier babel-eslint
    - cd src/client
    - eslint . 
  only:
    - merge_requests
    - master
  except:
    - branches    